name: master branch script

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-22.04

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEFAULT_HOST }}
          username: ${{ secrets.DEFAULT_USERNAME }}
          key: ${{ secrets.DEFAULT_KEY }}
          port: ${{ secrets.DEFAULT_PORT }}
          script: |
            cd /home/ubuntu/bayabas_pro_backend && # go to source directory
            git pull origin master && # pulling new push on 'master' branch
            git checkout . && # discard changes ex) package-lock.json

            export NVM_DIR=~/.nvm && # 'nvm' environment
            source ~/.nvm/nvm.sh && # setting up 'nvm'
            nvm install lts/iron && # install node 20
            nvm use lts/iron && # use node 20

            npm install && # install dependencies
            npm run update:dev
